apiVersion: apps/v1
kind: Deployment
metadata:
  name: preethi-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: preethi-springboot
  template:
    metadata:
      labels:
        app: preethi-springboot
    spec:
      containers:
        - name: springboot
          image: preethib1530/calci:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: preethi-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: preethi-springboot
